[phases.setup]
nixPkgs = [
  "cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg",
  "pkg-config", "python3", "nodePackages.node-gyp",
  "fontconfig", "dejavu_fonts", "liberation_fonts", "noto_fonts"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "npm start"