[phases.setup]
nixPkgs = [
  "cairo",
  "pango",
  "libpng",
  "libjpeg",
  "giflib",
  "librsvg",
  "pkg-config",
  "python3",
  "nodePackages.node-gyp",
  "nodejs_22",
  "fontconfig",
  "dejavu_fonts",
  "noto-fonts"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "npm start"